[project]
name = "wattsapp-automaitons"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "pyautogui>=0.9.54",
    "pywhatkit>=5.4",
    "requests>=2.32.3",
]
